# Generated by Django 3.2.7 on 2021-10-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('manicure', 'Маникюр'), ('pedicure', 'Педикюр'), ('design', 'Дизайн'), ('combo', 'Комбо'), ('cut', 'Снятие')], default='manicure', max_length=8),
        ),
    ]
